import "../vendor/jquery.jchart.js"
import "../modules/pie_chart/pie_chart.js"
import "../modules/pie_chart2/pie_chart2.js"
import "../modules/rangeSlider/range_slider.js"
import "../modules/rangeSlider2/range_slider2.js"
import "../modules/standart_btn/button.js"
import "../modules/stages/stages.js"
import "../modules/formElements/form.js"